const BASE_URL = "http://localhost:5000";

export const USER_API_ROUTES = {
  LOGIN: `${BASE_URL}/api/Auth/login`,
  REGISTER: `${BASE_URL}/api/Auth/register`,
  GET_SMOKING_STATUS: `${BASE_URL}/api/SmokingStatus/my-status`,
  POST_SMOKING_STATUS: `${BASE_URL}/api/SmokingStatus`,
  GET_ACHIEVEMENTS: `${BASE_URL}/api/Achievement`,
  GET_POSTS: `${BASE_URL}/api/CommunityPost`,
  GET_QUITPLAN: `${BASE_URL}/api/QuitPlan/my-plans`,
  GET_BRINKMAN: `${BASE_URL}/api/SmokingStatus/brinkman-index`,
  GET_USER_PROGESS_BY_DATE_RANGE: `${BASE_URL}/api/Progress/my-progress`,
  GET_SUGGEST_PLAN: `${BASE_URL}/api/Package/suggested-quit-plan`,
  POST_DAILY_PROGRESS: `${BASE_URL}/api/Progress/daily`,
  PUT_DAILY_PROGRESS: `${BASE_URL}/api/Progress`,
  GET_REPORT_DASHBOARD: `${BASE_URL}/api/Report/dashboard`,
  POST_APPOINTMENT: `${BASE_URL}/api/Appointment`,
  GET_APPOINTMENTS: `${BASE_URL}/api/Appointment/my`,
  GET_MESSAGES: `${BASE_URL}/api/Premium/chat/history`,
  GET_MY_COACH: `${BASE_URL}/api/Premium/coach/my-coach`,
  GET_CHAT_HISTORY: `${BASE_URL}/api/Premium/chat/history`,
  SEND_CHAT: `${BASE_URL}/api/Premium/chat/send`,
  POST_QUIT_PLAN: `${BASE_URL}/api/QuitPlan`,
  GET_MY_PLAN: `${BASE_URL}/api/QuitPlan/my-plans`,
  CHECK_PREMIUM_ACCESS: `${BASE_URL}/api/Package/premium-access`,
  UPGRADE_PACKAGE: `${BASE_URL}/api/Package/force-upgrade-premium`,
  GET_UNLOCKED_ACHIEVEMENTS: `${BASE_URL}/api/Achievement/unlocked`,
  GET_FEEDBACK: `${BASE_URL}/api/Feedback/by-coach`,
  POST_FEEDBACK: `${BASE_URL}/api/Feedback`,
};

export const COMMON_API = {
  GET_POSTS: `${BASE_URL}/api/CommunityPost`,
  GET_POPULAR_POSTS: `${BASE_URL}/api/CommunityPost/popular`,
  CREATE_POST: `${BASE_URL}/api/CommunityPost`,
  LIKE_POST: `${BASE_URL}/api/CommunityPost`,
  GET_EXPERIENCE_POST: `${BASE_URL}/api/CommunityPost/category`,
  GET_MY_POSTS: `${BASE_URL}/api/CommunityPost/my-posts`,
  PUT_MY_POST: `${BASE_URL}/api/CommunityPost`,
  DELETE_MY_POST: `${BASE_URL}/api/CommunityPost`,
  GET_LEADERBOARD: `${BASE_URL}/api/SmokingStatus/leaderboard/money-saved`,
  GET_COMMENTS: `${BASE_URL}/api/CommunityPost`,
  POST_COMMENT: `${BASE_URL}/api/CommunityPost`,
  GET_COACHES: `${BASE_URL}/api/Premium/coach/available-coaches`,
  ASSIGN_COACH: `${BASE_URL}/api/Premium/coach/assign`,
};

export const COACH_API_ROUTES = {
  GET_MY_CLIENTS: `${BASE_URL}/api/Coach/my-clients`,
  GET_CHAT_STATUS: `${BASE_URL}/api/Coach/chats`,
  GET_CHAT_MEMBER: `${BASE_URL}/api/Coach/chats`,
  SEND_PLAN: `${BASE_URL}/api/Coach/create-plan-for-client`,
  SEND_CHAT: `${BASE_URL}/api/Coach/chats`,
  GET_APPOINTMENTS: `${BASE_URL}/api/Appointment/coach`,
  GET_DIARY_USER: `${BASE_URL}/api/Coach/clients`,
  SENDNOTES_DIARY_USER: `${BASE_URL}/api/Coach/clients`,
  GET_MY_CLIENTS_PLANS: `${BASE_URL}/api/Coach/my-clients`,
  EDIT_QUIT_PLAN: `${BASE_URL}/api/Coach/clients`,
};
export const ADMIN_API_ROUTES = {
  GET_STATISTICS: `${BASE_URL}/api/Admin/statistics`,
  GET_STATISTICS_USERS: `${BASE_URL}/api/Admin/statistics/users`,
  GET_ACCOUNTS: `${BASE_URL}/api/Admin/accounts`,
  BAN_ACCOUNT: `${BASE_URL}/api/Admin/users`,
  UNBAN_ACCOUNT: `${BASE_URL}/api/Admin/statistics/users`,
  CHANGE_ROLE_ACCOUNT: `${BASE_URL}/api/Admin/change-role`,
  GET_COACHES: `${BASE_URL}/api/Admin/coaches`,
  CREATE_COACH: `${BASE_URL}/api/Admin/coaches`,
  UPDATE_COACH: `${BASE_URL}/api/Admin/coaches`,
};
